-- ============================================================
-- CECI - Classement central des grandes localités
-- Supabase / PostgreSQL
-- ============================================================

create table if not exists public.localites (
  id text primary key,
  parcelledenomination text not null,
  grande_localite text not null default 'À classer',
  statut text not null default 'À classer',
  commune text,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

create table if not exists public.groupes (
  nom text primary key,
  actif boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.journal_classement (
  id bigint generated by default as identity primary key,
  localite_id text references public.localites(id) on delete cascade,
  parcelledenomination text,
  ancienne_localite text,
  nouvelle_localite text,
  utilisateur uuid,
  created_at timestamptz not null default now()
);

alter table public.localites enable row level security;
alter table public.groupes enable row level security;
alter table public.journal_classement enable row level security;

-- MVP : utilisateurs authentifiés uniquement.
-- L'application utilise l'authentification anonyme Supabase.
drop policy if exists "auth select localites" on public.localites;
create policy "auth select localites" on public.localites
for select to authenticated using (true);

drop policy if exists "auth insert localites" on public.localites;
create policy "auth insert localites" on public.localites
for insert to authenticated with check (true);

drop policy if exists "auth update localites" on public.localites;
create policy "auth update localites" on public.localites
for update to authenticated using (true) with check (true);

drop policy if exists "auth delete localites" on public.localites;
create policy "auth delete localites" on public.localites
for delete to authenticated using (true);

drop policy if exists "auth select groupes" on public.groupes;
create policy "auth select groupes" on public.groupes
for select to authenticated using (true);

drop policy if exists "auth insert groupes" on public.groupes;
create policy "auth insert groupes" on public.groupes
for insert to authenticated with check (true);

drop policy if exists "auth update groupes" on public.groupes;
create policy "auth update groupes" on public.groupes
for update to authenticated using (true) with check (true);

drop policy if exists "auth delete groupes" on public.groupes;
create policy "auth delete groupes" on public.groupes
for delete to authenticated using (true);

drop policy if exists "auth select journal" on public.journal_classement;
create policy "auth select journal" on public.journal_classement
for select to authenticated using (true);

drop policy if exists "auth insert journal" on public.journal_classement;
create policy "auth insert journal" on public.journal_classement
for insert to authenticated with check (true);

grant select, insert, update, delete on public.localites to authenticated;
grant select, insert, update, delete on public.groupes to authenticated;
grant select, insert on public.journal_classement to authenticated;
grant usage, select on sequence public.journal_classement_id_seq to authenticated;

-- Realtime : exécuter si nécessaire dans SQL Editor.
alter publication supabase_realtime add table public.localites;
alter publication supabase_realtime add table public.groupes;

-- Index utiles
create index if not exists idx_localites_grande_localite on public.localites(grande_localite);
create index if not exists idx_localites_parcelle on public.localites(parcelledenomination);
create index if not exists idx_journal_created on public.journal_classement(created_at desc);
